import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');
import {
  fontBold, fontMedium, fontRegular, fontSemiBold, 
} from './customFont'

export const chatStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121b22',
    alignItems: 'center',
  },
  header: {
    width: '100%',
    // height: height * 8 / 100,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    position: 'absolute',
    display: 'flex',
    justifyContent: 'space-between',
    zIndex: 999,
    left: 0,
    top: 0,
    // backgroundColor: '#1f2c34',
    backgroundColor: '#0B1437',
  },
  backButton: {
    width: '12%',
    height: '80%',
  },
  backButtonIcon: {
    fontSize: 25,
    color: 'white',
  },
  backButtonImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginLeft: 0,
  },
  backButtonContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameButton: {
    width: '55%',
    height: '100%',
    marginLeft: 8,
  },
  nameContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 4,
  },
  groupChatUserName: {
    fontSize: 12,
    fontStyle: 'italic',
    ...fontMedium
  },
  nameText: {
    width: '100%',
    fontSize: 18,
    color: '#ecf4f6',
    marginBottom: -4,
    ...fontBold,
  },
  lastSeen: {
    color: '#cfd7dc',
    fontSize: 12,
    ...fontMedium
  },
  headerStories: {
    width: '25%',
    height: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  headerIcons: {
    width: '20%',
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  headerButton: {
    height: '80%',
    width: '33%',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIcon: {
    fontSize: 25,
    color: 'white',
    marginRight: 10,
  },
  messageContent: {
    width: '100%',
    minHeight: (height * 7) / 100,
    maxHeight: 'auto',
    position: 'absolute',
    // bottom: 7,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  messageBox: {
    flex: 1,
    height: '100%',
    backgroundColor: '#1f2c34',
    flexDirection: 'row',
    alignItems: 'flex-end',
    borderRadius: 30,
    marginRight: 10,
    position: 'relative'
  },
  messageButton: {
    width: 35,
    height: 35,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  messageInputContainer: {
    width: '75%',
    height: '100%',
    maxHeight: 125,
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 8,
    alignItems: 'center',
  },
  messageInput: {
    maxHeight: 125,
    width: '100%',
    color: 'white',
    ...fontRegular
  },
  messageIcon: {
    fontSize: 25,
    color: '#8b99a4',
  },
  voiceMessageButton: {
    width: 55,
    height: 55,
    borderRadius: 30,
    backgroundColor: '#00a884',
    justifyContent: 'center',
    alignItems: 'center',
  },
  voiceMessageIcon: {
    fontSize: 30,
    color: 'white',
  },
  chatContainer: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    bottom: 0,
    // paddingHorizontal:10,
    paddingBottom: 90,
    justifyContent: 'flex-end',
    zIndex: -1,
    paddingTop: 62,
  },
  chatBoxRight: {
    backgroundColor: '#E0F6CA',
    paddingHorizontal: 15,
    paddingVertical: 6,
    marginLeft: '10%',
    marginRight: '5%',
    maxWidth: '80%',
    minWidth: '30%',
    alignSelf: 'flex-end',
    borderRadius: 10,
    position: 'relative'
  },
  chatBoxLeft: {
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    paddingVertical: 6,
    marginLeft: '5%',
    maxWidth: '80%',
    minWidth: '30%',
    alignSelf: 'flex-start',
    borderRadius: 10,
  },
  loading:{
    position:'absolute',
    right: 1,
    top: -5
  },
  messageContainer: {
    paddingTop: 4,
  },
  chatText: {
    color: '#000',
    fontSize: 16,
    ...fontSemiBold
  },
  chatContactText: {
    color: '#366edb',
    fontSize: 20,
    paddingTop: 4,
    ...fontBold
  },
  chatBottomText: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  emojiLayout: {
    position: 'absolute',
    top: 24,
    width: 30,
    height: 30,
    borderRadius: 50,
    backgroundColor: '#FFF',
    padding: 6,
  },
  avatarGroupStyle: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  groupAvatarFoto: {
    width: '50%',
    borderWidth: 1.5,
    borderColor: 'white',
  },
  moreAvatarCount: {
    position: 'absolute',
    width: '40%',
    height: '40%',
    borderRadius: 1000,
    backgroundColor: '#121b22',
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  blankEmoji: {
    width: 30,
    height: 15,
  },
  iconEmoji: {
    borderRadius: 50,
    textAlign: 'center',
    verticalAlign: 'middle',
  },
  emojiLeft: {
    right: 0,
  },
  emojiRight: {},
  chatTime: {
    right: 0,
    marginLeft: 'auto',
    fontSize: 12,
    marginRight: 10,
    ...fontRegular,
  },
  backGrounImage: {
    position: 'absolute',
    zIndex: -1,
    width: width,
    height: '100%',
    objectFit: 'scale-down',
  },
  leftArrow: {
    position: 'absolute',
    backgroundColor: '#fff',
    width: 30,
    height: 25,
    bottom: 0,
    borderBottomRightRadius: 25,
    left: -15,
  },
  rightArrow: {
    position: 'absolute',
    backgroundColor: '#E0F6CA',
    width: 30,
    height: 25,
    bottom: 0,
    borderBottomLeftRadius: 25,
    right: -15,
  },
  leftArrowOverlap: {
    position: 'absolute',
    backgroundColor: '#121b22',
    width: 20,
    height: 35,
    bottom: -6,
    borderBottomRightRadius: 40,
    left: -20,
  },
  rightArrowOverlap: {
    position: 'absolute',
    backgroundColor: '#121b22',
    width: 20,
    height: 35,
    bottom: -6,
    borderBottomLeftRadius: 40,
    right: -20,
  },
  circleButton: {
    backgroundColor: '#00a884',
    alignItems: 'center',
    justifyContent: 'center',
    width: 55,
    height: 55,
    borderRadius: 30,
  },
  slideBtnTitle: {
    color: '#5856D6',
    textAlign: 'right',
    fontSize: 14,
    ...fontRegular
  },
  slideBtnContainer: {
    backgroundColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 0,
    elevation: 0,
    shadowOpacity: 0,
    margin: 0,
    padding: 0,
  },
  slideBtnUnderlay: {
    backgroundColor: 'transparent',
    margin: 0,
    padding: 0,
  },
  slideBtnTitleContainer: {
    backgroundColor: 'white',
    margin: 0,
    padding: 0,
  },
  audioRecorderContainer: {
    justifyContent: 'center',
    backgroundColor: 'white',
    height: 55,
    borderRadius: 30
  },
  recordTimeContainer: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    left: 10,
  },
  recordIcon: {
    fontSize: 24,
    color: 'red',
  },
  recordTime: {
    fontSize: 16,
  },
  viewBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewBarWrapper: {
    width: 200,
    marginLeft: 4,
  },
  viewBar: {
    backgroundColor: '#ccc',
    height: 4,
    alignSelf: 'stretch',
  },
  viewBarPlay: {
    backgroundColor: '#5856D6',
    height: 4,
    width: 0,
  },
  viewPlayer: {
    alignSelf: 'stretch',
    alignItems: 'center',
    width: '100%',
  },
  playStatusTxt: {
    marginTop: 8,
    color: '#ccc',
  },
  txtCounter: {
    marginTop: -4,
    fontSize: 12,
    marginLeft: 'auto',
  },
  controlBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 22,
    height: 22,
  },
  controls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recordPlayerControlBtnIcon: {
    fontSize: 26,
    color: '#5856D6',
    marginLeft: -6,
    marginTop: -2,
  },
  pageTitle: {
    fontSize: 22,
    color: '#ecf4f6',
    ...fontBold
  },
  participants: {
    flexDirection: 'row',
    padding: 8,
    borderColor: '#eae3d9',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    backgroundColor: '#121b22',
    minWidth: width,
  },
  badge: {
    width: 18,
    height: 18,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: -2,
    bottom: -2,
    borderColor: '#121b22',
    borderWidth: 2,
  },
  createGroupBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#00a884',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 16,
  },
  createGroupInputContainer: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: '#d1eed3',
  },
  messageTrigger: {
    position: 'absolute',
    left: -5,
    bottom: -5,
    paddingBottom: 6,
    paddingTop: 0,
    paddingHorizontal: 5,
  },
  createGroupInput: {
    flex: 1,
    color: 'black',
    fontSize: 18,
    borderColor: 'black',
    borderBottomWidth: 1,
    ...fontRegular
  },
  checkMessageIcon: {
    position: 'absolute',
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    borderColor: '#121b22',
    borderWidth: 1,
    backgroundColor: 'green',
    left: -10,
    bottom: -15,
    zIndex: 2,
  },
  contactViewModal: {
    backgroundColor: '#eee',
    padding: 20,
    borderRadius: 10
  }
});
